spring:
  application:
    name: mansShop_boot
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    generate-ddl: off
    database: mysql

  devtools:
    livereload:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/mansShop?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234

server:
  port: 8080

logging:
  file:
    path: logback-spring

