spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
    generate-ddl: off
    database: mysql

  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB

  datasource:
    url: jdbc:mysql://localhost:3306/mansShopTest?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: dm1234
    hikari.maximum-pool-size: 30

  data:
    redis:
      host: localhost
      port: 6380

  rabbitmq:
    host: localhost
    port: 5673
    username: admin
    password: admin1212
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000ms
          max-attempts: 5
          multiplier: 2.0
        auto-startup: true
        missing-queues-fatal: false

#  mailhog
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls.enable: false
          starttls.required: false

server:
  port: 8081

logging:
  file:
    path: logback-test-spring
  level:
    org.hibernate.sql: debug
    org.hibernate.tool.schema.internal: debug